## **For Clean Installation of PyTorch use following commands:**

- **pip cache purge**
- **pip install --no-cache-dir torch torchvision torchaudio**

In [1]:
import torch

In [2]:
# Creating Tensors
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [3]:
# Creating a Random Tensor
x = torch.rand(5, 3)
print(x)

tensor([[0.6038, 0.5942, 0.6866],
        [0.8303, 0.9764, 0.7405],
        [0.0639, 0.6991, 0.4703],
        [0.4789, 0.3103, 0.3007],
        [0.1910, 0.1622, 0.4575]])


In [4]:
# Creating a Zeros or Ones Tensor
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# Checking Tensor Properties

print("Shape:", x.shape)     # Tensor shape
print("Data Type:", x.dtype) # Data type
print("Device:", x.device)   # CPU or GPU
print("Layout:", x.layout)   # Memory layout

Shape: torch.Size([5, 3])
Data Type: torch.int64
Device: cpu
Layout: torch.strided


In [8]:
# Reshaping Tensors
x = torch.arange(1, 10)  # Tensor from 1 to 9
reshaped_x = x.view(3, 3)  # Reshape to 3x3
print(x)
print(reshaped_x)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### **Tensor Operations**

In [9]:
# Basic Math Operations
a = torch.tensor([3, 5, 7])
b = torch.tensor([1, 2, 3])
print(a + b)  # Addition
print(a - b)  # Subtraction
print(a * b)  # Element-wise multiplication
print(a / b)  # Element-wise division

tensor([ 4,  7, 10])
tensor([2, 3, 4])
tensor([ 3, 10, 21])
tensor([3.0000, 2.5000, 2.3333])


In [ ]:
# Matrix Multiplication
A = torch.rand(2, 3)
B = torch.rand(3, 2)
C = torch.matmul(A, B)  # Matrix multiplication
print(C)

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
print(torch.matmul(a, b)) # Matrix multiplication

tensor([[0.8462, 0.7236],
        [0.4357, 0.5780]])
tensor([[19, 22],
        [43, 50]])


In [12]:
# Using GPU for Computation
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [13]:
# Using GPY for Computation
device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.tensor([1, 2, 3], device=device)
print(x)

tensor([1, 2, 3])


In [14]:
# Converting Between NumPy and PyTorch
torch_tensor = torch.tensor([1, 2, 3])
numpy_array = torch_tensor.numpy()
print(numpy_array)

[1 2 3]


In [15]:
# NumPy to PyTorch
import numpy as np
np_array = np.array([4, 5, 6])
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)

tensor([4, 5, 6])


### **Autograd (Automatic Differentiation)**

In [16]:
# Enabling Gradient Computation
x = torch.tensor(2.0, requires_grad=True)
y = x ** 3 + 5 * x  # Function y = x^3 + 5x
y.backward()  # Compute derivative
print(x.grad)  # dy/dx = 3x^2 + 5

tensor(17.)


In [17]:
# Saving and Loading Tensors
torch.save(x, "tensor.pth")
x = torch.load("tensor.pth")
print(x)

tensor(2., requires_grad=True)


In [22]:
torch.is_nonzero(torch.tensor([0.]))
torch.is_nonzero(torch.tensor([1.5]))
torch.is_nonzero(torch.tensor([False]))
torch.is_nonzero(torch.tensor([3]))

True

In [24]:
x = torch.tensor([1, 2, 3]) # Returns True if obj is a PyTorch tensor.
torch.is_tensor(x)
torch.is_storage(x) # Returns True if obj is a PyTorch storage object.
torch.is_complex(x) # Returns True if obj is a PyTorch complex tensor.
torch.is_conj(x) # Returns True if obj is a PyTorch conjugate tensor.
torch.is_floating_point(x) # Returns True if obj is a PyTorch floating point tensor.
# torch.is_nonzero(x) # Returns True if obj is a PyTorch tensor with non-zero elements.
torch.is_same_size(x, x) # Returns True if obj1 and obj2 have the same size.




True

# **Building Neural Networks (torch.nn)**

In [25]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [ ]:
# Define a simple Feedforward Neural Network (FNN) with one hidden layer.
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = x.view(-1, 28 * 28)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [ ]:
# a simple Feedforward Neural Network (FNN) with one hidden layer.
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(4, 8)  # Input: 4 neurons → Hidden: 8 neurons
        self.fc2 = nn.Linear(8, 3)  # Hidden: 8 neurons → Output: 3 neurons

    def forward(self, x):
        x = F.relu(self.fc1(x))  # Activation function (ReLU)
        x = self.fc2(x)          # Output layer (No activation for raw logits)
        return x


# Explanation:

# fc1: Fully connected layer (Linear layer).
# fc2: Another fully connected layer.
# F.relu(): Activation function (ReLU).

In [ ]:
# Create an Instance of the Model
model_1 = Net()
model_2 = NeuralNetwork()
print(model_1)
print(model_2)

Net(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=10, bias=True)
)
NeuralNetwork(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=3, bias=True)
)


In [31]:
# Define Loss Function & Optimizer
criterion = nn.CrossEntropyLoss()  # For classification
optimizer_1 = optim.Adam(model_1.parameters(), lr=0.01)  # Adam optimizer
optimizer_2 = optim.SGD(model_2.parameters(), lr=0.01)  # SGD optimizer

In [33]:
# Example dataset (4 input features, 3 output classes)
X = torch.rand(10, 4)  # 10 samples, each with 4 features
y = torch.randint(0, 3, (10,))  # Random labels (0, 1, or 2)

# Training loop
epochs = 100
for epoch in range(epochs):
    optimizer_2.zero_grad()  # Reset gradients
    outputs = model_2(X)  # Forward pass
    loss = criterion(outputs, y)  # Compute loss
    loss.backward()  # Backpropagation
    optimizer_2.step()  # Update weights

    if (epoch+1) % 20 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')


Epoch [20/100], Loss: 0.9990
Epoch [40/100], Loss: 0.9768
Epoch [60/100], Loss: 0.9571
Epoch [80/100], Loss: 0.9394
Epoch [100/100], Loss: 0.9236


In [35]:
# Saving & Loading the Model
torch.save(model_2.state_dict(), "model.pth")
model_2.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>

In [36]:
# Load the model
loaded_model = NeuralNetwork()
loaded_model.load_state_dict(torch.load("model.pth"))
loaded_model.eval()  # Set model to evaluation mode

NeuralNetwork(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=3, bias=True)
)

## **Convolutional Neural Networks (CNNs)**

In [37]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms

# **Load and Preprocess Image Data**

In [38]:
# Define transformations
transform = transforms.Compose([
    transforms.ToTensor(), 
    transforms.Normalize((0.5,), (0.5,))
])

# Download and load the training data
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=32, shuffle=True)

# Download and load the test data
testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=32, shuffle=False)


100.0%


## **Define the CNN Model**

In [39]:
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()

        # Convolutional layers
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1)
        
        # Fully connected layers
        self.fc1 = nn.Linear(32 * 8 * 8, 128)  # 32 channels, 8x8 feature map
        self.fc2 = nn.Linear(128, 10)  # 10 output classes

        # Pooling layer
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))  # First conv layer + ReLU + Max Pooling
        x = self.pool(F.relu(self.conv2(x)))  # Second conv layer + ReLU + Max Pooling
        x = torch.flatten(x, 1)  # Flatten for fully connected layer
        x = F.relu(self.fc1(x))  # First FC layer + ReLU
        x = self.fc2(x)  # Output layer (No activation since we'll use CrossEntropyLoss)
        return x

In [40]:
# Initialize Model, Loss Function & Optimizer
model = CNN()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# **Train the CNN Model**

In [41]:
epochs = 5

for epoch in range(epochs):
    running_loss = 0.0

    for images, labels in trainloader:
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()

    print(f'Epoch {epoch+1}/{epochs}, Loss: {running_loss/len(trainloader):.4f}')


Epoch 1/5, Loss: 1.3716
Epoch 2/5, Loss: 1.0211
Epoch 3/5, Loss: 0.8754
Epoch 4/5, Loss: 0.7763
Epoch 5/5, Loss: 0.6935


# **Test the Model**

In [42]:
correct = 0
total = 0

with torch.no_grad():
    for images, labels in testloader:
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total
print(f'Accuracy on test set: {accuracy:.2f}%')

Accuracy on test set: 70.08%


# **Fine-tuning with Transfer Learning (e.g., ResNet, VGG, Xception)**