# *For Clean Installation use following commands:*

- *pip cache purge*
- *pip install --no-cache-dir torch torchvision torchaudio*

In [1]:
import torch

In [2]:
# Creating Tensors
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [3]:
# Creating a Random Tensor
x = torch.rand(5, 3)
print(x)

tensor([[0.6038, 0.5942, 0.6866],
        [0.8303, 0.9764, 0.7405],
        [0.0639, 0.6991, 0.4703],
        [0.4789, 0.3103, 0.3007],
        [0.1910, 0.1622, 0.4575]])


In [4]:
# Creating a Zeros or Ones Tensor
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# Checking Tensor Properties

print("Shape:", x.shape)     # Tensor shape
print("Data Type:", x.dtype) # Data type
print("Device:", x.device)   # CPU or GPU
print("Layout:", x.layout)   # Memory layout

Shape: torch.Size([5, 3])
Data Type: torch.int64
Device: cpu
Layout: torch.strided


In [8]:
# Reshaping Tensors
x = torch.arange(1, 10)  # Tensor from 1 to 9
reshaped_x = x.view(3, 3)  # Reshape to 3x3
print(x)
print(reshaped_x)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### **Tensor Operations**

In [9]:
# Basic Math Operations
a = torch.tensor([3, 5, 7])
b = torch.tensor([1, 2, 3])
print(a + b)  # Addition
print(a - b)  # Subtraction
print(a * b)  # Element-wise multiplication
print(a / b)  # Element-wise division

tensor([ 4,  7, 10])
tensor([2, 3, 4])
tensor([ 3, 10, 21])
tensor([3.0000, 2.5000, 2.3333])


In [ ]:
# Matrix Multiplication
A = torch.rand(2, 3)
B = torch.rand(3, 2)
C = torch.matmul(A, B)  # Matrix multiplication
print(C)

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
print(torch.matmul(a, b)) # Matrix multiplication

tensor([[0.8462, 0.7236],
        [0.4357, 0.5780]])
tensor([[19, 22],
        [43, 50]])


In [12]:
# Using GPU for Computation
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [13]:
# Using GPY for Computation
device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.tensor([1, 2, 3], device=device)
print(x)

tensor([1, 2, 3])


In [14]:
# Converting Between NumPy and PyTorch
torch_tensor = torch.tensor([1, 2, 3])
numpy_array = torch_tensor.numpy()
print(numpy_array)

[1 2 3]


In [15]:
# NumPy to PyTorch
import numpy as np
np_array = np.array([4, 5, 6])
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)

tensor([4, 5, 6])


### **Autograd (Automatic Differentiation)**

In [16]:
# Enabling Gradient Computation
x = torch.tensor(2.0, requires_grad=True)
y = x ** 3 + 5 * x  # Function y = x^3 + 5x
y.backward()  # Compute derivative
print(x.grad)  # dy/dx = 3x^2 + 5

tensor(17.)


In [17]:
# Saving and Loading Tensors
torch.save(x, "tensor.pth")
x = torch.load("tensor.pth")
print(x)

tensor(2., requires_grad=True)


In [22]:
torch.is_nonzero(torch.tensor([0.]))
torch.is_nonzero(torch.tensor([1.5]))
torch.is_nonzero(torch.tensor([False]))
torch.is_nonzero(torch.tensor([3]))

True

In [24]:
x = torch.tensor([1, 2, 3]) # Returns True if obj is a PyTorch tensor.
torch.is_tensor(x)
torch.is_storage(x) # Returns True if obj is a PyTorch storage object.
torch.is_complex(x) # Returns True if obj is a PyTorch complex tensor.
torch.is_conj(x) # Returns True if obj is a PyTorch conjugate tensor.
torch.is_floating_point(x) # Returns True if obj is a PyTorch floating point tensor.
# torch.is_nonzero(x) # Returns True if obj is a PyTorch tensor with non-zero elements.
torch.is_same_size(x, x) # Returns True if obj1 and obj2 have the same size.




True